services:
  - type: web
    name: frontend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    branch: main
    ports:
      - 80

  - type: web
    name: backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    autoDeploy: true
    branch: main
    ports:
      - 3000
    envVars:
      - key: PORT
        value: 3000
