services:
  - type: web
    name: frontend
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    plan: free
    autoDeploy: true
    branch: main

  - type: web
    name: backend
    env: docker
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    plan: free
    autoDeploy: true
    branch: main
 
